### ISSUE TITLE
test_contract is unreliable on git

### ISSUE THREAD

**Issue by clamdad** [tellor-io/pytelliot#127]
This unit test fails often on git, making it difficult to validate PRs.

**Comment by tallywiesenberg** [comment]
When you say “on git”, Do you mean when you check our the branch and test it locally?

**Comment by clamdad** [comment]
Sorry for the lack of detail!

The last PR was just doc changes.  It passed locally, then failed once in the PR check, then passed after I force re-ran it.
Then when I merged it to Main, it failed again.  Hence the master currently has a "failed" badge.
It's usually the 3.9 or 3.8 test that fails, kind of randomly.

Here are some examples:
- https://github.com/tellor-io/pytelliot/runs/4079825984?check_suite_focus=true
- https://github.com/tellor-io/pytelliot/runs/4079825753?check_suite_focus=true

**Comment by tallywiesenberg** [comment]
Aha, good catch. I wrote that test in the context of tellor playground. Now that we have switched to testing TellorX on rinkeby, I think it is redundant.

**Comment by tallywiesenberg** [comment]
I also marked to skip this test in my PR
