### ISSUE TITLE
Base class to standardize web3/contract connection

### ISSUE THREAD

**Issue by tallywiesenberg** [tellor-io/pytelliot#28]
As the number of roles we implement in telliot grows, I propose we implement a parent class for voters, reporters, tippers, disputers, etc that we can use to ensure that each role uses the same web3/contract connection.

This class should include:
- eth_account.account.Account (an eth account from pk)
- Web3 connection object
- Tellor contract object

**Comment by clamdad** [comment]
I made the class below for another project that might be a good starting point (it's in Atom, but could be converted to dataclass or pydantic).

Probably no need for voters, reporters... to be members of the same parent class.  
They can each all have an Endpoint, though, as an attribute they can use for the connection.

```python
class RPCEndpoint(Endpoint):
    """ JSON RPC Endpoint
    """
    #: Blockchain Name
    chain = Enum(*supported_networks)

    #: Network Name (e.g. 'mainnet', 'testnet', 'rinkebey')
    network = Str()

    #: Provider Name (e.g. 'Infura')
    provider = Str()

    #: URL (e.g. 'https://mainnet.infura.io/v3/<project_id>')
    url = Str()

    #: Web3 Connection
    web3 = Typed(Web3)

    def connect(self):
        self.web3 = Web3(Web3.HTTPProvider(self.url))
        connected = self.web3.isConnected()
        if connected:
            print("Connected to {}".format(self))
        else:
            print("Could not connect to {}".format(self))

        return self.web3

    def close(self):
        self.web3 = None
```

**Comment by tallywiesenberg** [comment]
Oh that’s awesome! Just to clarify, do you mean “ to be members of the same parent class” or “ to be members of the same parent object”?

**Comment by clamdad** [comment]
I should have said that they don't need to **inherit** from the same parent class.  These or any other objects could have an endpoint and use it to manage it's connection to web3.
