### ISSUE TITLE
remove rinkeby from btc/usd plugin module name

### ISSUE THREAD

**Issue by oraclown** [tellor-io/pytelliot#31]

**Comment by oraclown** [comment]
I'm guessing we'll just have the simple example in the docs pass another flag like `telliot report --network rinkeby`, or specify that rinkeby is used in the default config file

**Comment by clamdad** [comment]
BTC/USD is not really needed in the name, either.

It seems the Reporter class would need a reference to the data feed ID, which could be passed in through the constructor.
The data feed in turn references the query that it is answering, which in turn has the data type of the answer.  So it seems that the reporter could be a generic class, and users could create their own data feeds and pass it to the reporter class when instantiating.
